### ISSUE TITLE
 C++ library <neo4j-client.h> enable only insecure connections 

### ISSUE THREAD

**Issue by borneq** [cleishm/libneo4j-client#16]
I try
neo4j_config_t *config = neo4j_new_config();
neo4j_connection_t *connection =
            neo4j_connect("neo4j://neo4j:pass@localhost:7687", config,  NEO4J_CONNECT_DEFAULT);
instead of NEO4J_INSECURE
but is bas

**Comment by cleishm** [comment]
Hi @borneq: I think your comment was cut off. What's the problem you're having?

**Comment by borneq** [comment]
I am previously using Java library
```
public Neo4JOut(String ip, String user, String password, boolean encryption) {
		Config cfgSSL;
		if (encryption)
			cfgSSL = Config.build().withEncryptionLevel(Config.EncryptionLevel.REQUIRED).toConfig();
		else
			cfgSSL = Config.build().withEncryptionLevel(Config.EncryptionLevel.NONE).toConfig();
		driver = GraphDatabase.driver("bolt://" + ip, AuthTokens.basic(user, password), cfgSSL);
		session = driver.session();
	}
```
In C library I can't find equivalent of Config, build().withEncryptionLevel

**Comment by cleishm** [comment]
In the C library, the use of encryption is indicated in the flags passed to `neo4j_connect`. The following code is roughly equivalent to your Java code:

```C
neo4j_config_t *config = neo4j_new_config();
if (config == NULL) {
    // handle error
}
if (neo4j_config_set_username(config, user)) {
  // handle error
}
if (neo4j_config_set_password(config, password)) {
  // handle error
}
neo4j_connection_t *connection = neo4j_tcp_connect(ip, 7687, config,
        NEO4J_CONNECT_DEFAULT | (encryption? NEO4J_INSECURE | 0));
if (connection == NULL) {
  // handle error
}
neo4j_session_t *session = neo4j_new_session(connection);
if (session == NULL) {
  // handle error
}
```

Note that I used [`neo4j_tcp_connect`](https://cleishm.github.io/libneo4j-client/doc/latest/neo4j-client_8h.html#af5b6c7e6f637fc5ee1a1cd652baf351b) rather than [`neo4j_connect`](https://cleishm.github.io/libneo4j-client/doc/latest/neo4j-client_8h.html#a84dff5eae1df5b5b27cc160ca867d467) because you seem to already have the IP as a variable, and [`neo4j_tcp_connect`](https://cleishm.github.io/libneo4j-client/doc/latest/neo4j-client_8h.html#af5b6c7e6f637fc5ee1a1cd652baf351b) allows you to use it directly rather than having to build a URI.

**Comment by cleishm** [comment]
Seems this is resolved.
