### ISSUE TITLE
result stream closed error

### ISSUE THREAD

**Issue by ludovic-pl** [cleishm/libneo4j-client#18]
I create a result_stream with the function neo4j_run.
When i close this stream i get the signal SIGARBRT with the following error message: 

>  result_stream.c:549: run_rs_close: Assertion `results->refcount == 0' failed.

But if i run my code multiple times, it work in the end.
In my code i do some insertion and fetch with different  threads (connection and session different)
The fetch and add are not on node of same label.

**Comment by cleishm** [comment]
Hi! Can you share the test code for this issue?

**Comment by ludovic-pl** [comment]
Hi!
It's a bit difficult to generate some sample code.
But with perror i had more insight of the error. It tell me that i can't have concurrent session.

**Comment by cleishm** [comment]
I'll need some way to reproduce the issue to really understand what is going on. Can you please try to create some code that reproduces it?

**Comment by ludovic-pl** [comment]
I'll try to have some sample code to reproduce the issue.

**Comment by ludovic-pl** [comment]
[issue_libneo4j.zip](https://github.com/cleishm/libneo4j-client/files/922425/issue_libneo4j.zip)
For the moment i have this sample, but it doesn't show the error i got.
For now it send some std::system_error

**Comment by cleishm** [comment]
Thanks. I've copied that code to https://gist.github.com/cleishm/ba8ddc3775795bc074b613ddb0b9148c/4229130305b2f08134dd082a2185b9079a160247.

The first thing I notice is that you're [cleaning up `vector_thread_insert`](https://gist.github.com/cleishm/ba8ddc3775795bc074b613ddb0b9148c/4229130305b2f08134dd082a2185b9079a160247#file-main-cpp-L57-L63) before [cleaning up `vector_thread_fetch`](https://gist.github.com/cleishm/ba8ddc3775795bc074b613ddb0b9148c/4229130305b2f08134dd082a2185b9079a160247#file-main-cpp-L65-L71). However, the threads stored in `vector_thread_fetch` depend on the threads in `vector_thread_insert` (they join these threads). Because of the cleanup order, the thread in `vector_thread_insert` [could be deleted](https://gist.github.com/cleishm/ba8ddc3775795bc074b613ddb0b9148c/4229130305b2f08134dd082a2185b9079a160247#file-main-cpp-L62) before it is[ joined in the `vector_thread_fetch` thread](https://gist.github.com/cleishm/ba8ddc3775795bc074b613ddb0b9148c/4229130305b2f08134dd082a2185b9079a160247#file-main-cpp-L36-L37), causing an error.

[Swapping the cleanup order fixes this](https://gist.github.com/cleishm/ba8ddc3775795bc074b613ddb0b9148c#file-main-cpp-L57-L71), and now I cannot reproduce any error.

However, I suggest being very, very careful using a `neo4j_connection` across multiple threads. The connection, session or result streams are not synchronised and should not be accessed concurrently from multiple threads.

**Comment by ludovic-pl** [comment]
Ok thank you for your quick reply.
In my project i have to use multiple thread. With your warrant i'll make some change about the access of the database. But i have one question.
I understand that the connection and session cannot be accessed concurrently, but can i generate a result streams in each threads ? or do i need to create only one stream at a given time ?

**Comment by cleishm** [comment]
No, you should not concurrently access result streams from the same connection+session.

While you can send multiple statements on a single connection+session, and thus have multiple open result streams, they are actually processed in serial. Each result stream is completely retrieved before the next.

If you want true concurrent access, you must use separate connections. This is a constraint of the underlying protocol (BOLT).

**Comment by ludovic-pl** [comment]
I try your solution and it resolve my problem. I had a thread race.
Thank you very much.
