### ISSUE TITLE
support running the CLI in a crontab job

### ISSUE THREAD

**Issue by bradacina** [cleishm/libneo4j-client#35]
It seems that the CLI wants a TTY even though I specify --non-interactive and pass the password on the command line as an argument. Running it inside a crontab job like this:

`neo4j-client --insecure --no-known-hosts --non-interactive -u $NEO4JUSER -p $NEO4JPASSWORD -o create_neo4j_index.log -i scripts/create_neo4j_devices_index.cy $NEO4JURL
`

comes back with:
`Can't open /dev/tty: No such device or address`

**Comment by cleishm** [comment]
Thanks for the report. I've not seen it return that error before when checking for the TTY - but it certainly is one that should be skipped. I've patched it in 01ff2d21707fc2ec1827f45fc312f95a695da6ed, so it should be fixed in the next release. If you can test it using a master build, that would be great too.

**Comment by davisford** [comment]
@cleishm could you do a new release with this fix in it?  I have the same problem, and am using the latest release 2.2.0 which I have confirmed does _not_ contain this fix.

**Comment by monstrfolk** [comment]
Also facing this issue.
